import Document, { Html, Head, Main, NextScript } from 'next/document'

const APP_NAME = '가영아 노래 불러줘'

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    return await Document.getInitialProps(ctx)
  }

  render() {
    return (
      <Html lang="ko-KR">
        <Head>
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Cute+Font&family=Noto+Serif+KR:wght@400;700&display=swap"
          />
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard-dynamic-subset.css"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
          <link
            rel="manifest"
            href="/manifest.json"
          />
          <link
            rel="apple-touch-icon"
            href="/apple-180x180.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="640x1136"
            href="/splash-640x1136.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="750x1334"
            href="/splash-750x1334.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="828x1792"
            href="/splash-828x1792.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1125x2436"
            href="/splash-1125x2436.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1136x640"
            href="/splash-1136x640.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1170x2532"
            href="/splash-1170x2532.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1242x2208"
            href="/splash-1242x2208.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1242x2688"
            href="/splash-1242x2688.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1284x2778"
            href="/splash-1284x2778.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1334x750"
            href="/splash-1334x750.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1536x2048"
            href="/splash-1536x2048.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1620x2160"
            href="/splash-1620x2160.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1668x2224"
            href="/splash-1668x2224.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1668x2388"
            href="/splash-1668x2388.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="1792x828"
            href="/splash-1792x828.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2048x1536"
            href="/splash-2048x1536.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2048x2732"
            href="/splash-2048x2732.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2160x1620"
            href="/splash-2160x1620.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2208x1242"
            href="/splash-2208x1242.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2224x1668"
            href="/splash-2224x1668.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2388x1668"
            href="/splash-2388x1668.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2436x1125"
            href="/splash-2436x1125.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2532x1170"
            href="/splash-2532x1170.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2688x1242"
            href="/splash-2688x1242.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2732x2048"
            href="/splash-2732x2048.png"
          />
          <link
            rel="apple-touch-startup-image"
            sizes="2778x1284"
            href="/splash-2778x1284.png"
          />
          <meta
            name='application-name'
            content={APP_NAME}
          />
          <meta
            name='apple-mobile-web-app-capable'
            content='yes'
          />
          <meta
            name='apple-mobile-web-app-status-bar-style'
            content='black-translucent'
          />
          <meta
            name='apple-mobile-web-app-title'
            content={APP_NAME}
          />
          <meta
            name='mobile-web-app-capable'
            content='yes'
          />
          <meta
            name='theme-color'
            content='#d75d73'
          />
          <meta
            name="theme-color"
            content="#fff"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
